<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="/css/bootstrap.min.css">
   <script src="/js/jquery.min.js"></script>
   <script src="/js/bootstrap.min.js"></script>
   <style type="text/css">
      .container hr{
      	   margin-bottom: 0px;
        }
      .container address{
	       font-size: 16px;
        }
   </style>
   <title>403 Forbidden</title>	
</head>
<body>
	<div class="container text-center">
			<h1>403&nbsp;Forbidden</h1>	
			<hr/>
			<address>nginx/1.8.1</address>	
	</div>
</body>
</html>