<?php
$flashMessage = $this->flashMessenger()->getMessages();
$title = "登录";
$this->headtitle($title);

if (count($flashMessage)) :
?>
<div class="row">
	<ul>
        <?php
      foreach ($flashMessage as $msg) :
        foreach ($msg as $type => $message) :
          ?>
            <li><span class="<?= $type; ?>"><?= $message; ?></span></li>
        <?php endforeach; ?>
      <?php endforeach; ?>
    </ul>
    <?php endif; ?>
    <?php if(isset($this->messages)) : ?>
    <ul>
        <?php foreach ($this->messages as $type => $msg) : ?>
        <li><span class="<?= $type; ?>"><?= $msg; ?></span></li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

<div class="row">
	<div class="col-md-5">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">登录</h3>
			</div>
			<div class="panel-body">
			    <?php
                $form = $this->loginForm;
                $form->prepare();
                echo $this->form()->openTag($form);
                 ?>
            <div class="form-group">
                 <?= $this->formlabel($form->get('account'));?>
                 <div class="col-sm-8">
                 	<?= $this->formElement($form->get('account')); ?>
                 	<?= $this->formElementErrors($form->get('account'));?>
                 </div>                 
             </div>
             <div class="form-group">
             	 <?= $this->formlabel($form->get('password'));?>
                 <div class="col-sm-8">
                 	<?= $this->formElement($form->get('password')); ?>
                 	<?= $this->formElementErrors($form->get('password'));?>
                 </div>
             </div>
             <div class="form-group">
             	 <?= $this->formlabel($form->get('captcha'));?>
                 <div class="col-sm-8">
                 	<?= $this->formRow($form->get('loginCsrf'));?>
                 	<?= $this->formcaptcha($form->get('captcha'));?>
                 	<?= $this->formElementErrors($form->get('captcha'));?>
                 </div>
             </div>
             <div class="form-group">
                 <div class="col-sm-3">
                 	<?= $this->formElement($form->get('submit'));?>
                 </div>
                 <div class="col-sm-3">
                 	<a class="btn btn-primary form-control" href="
                 	<?= $this->escapehtml('/admin/findpass')?>">找回密码</a>
                 </div>
             </div>
             <?= $this->form()->closeTag($form);?>
            </div>
		</div>
	</div>
</div>