<?php

$title = '删除博客';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete
<?php echo $this->escapeHtml($this->post->title);?>
</p>
<?php
    $url = $this->url('blog', array(
        'action' => 'delete',
        'id'=> $this->id,
    ));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo (int) $this->post->id; ?>" />
<input type="submit" name="del" class="btn btn-default" value="Yes" />
<input type="submit" name="del" class="btn btn-default" value="No" />
</div>
</form>