<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Skeleton Application'))->setSeparator(' |')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css')); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/custom.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                    	<img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Myblog"/>                   		
                      </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                        	<a href="<?php echo $this->url('home') ?>">
                        		<?php echo $this->translate('Home') ?>
                        	</a>
                        </li>
                    <?php 
                        $config = new \Zend\Config\Reader\Xml();
                        $class = $config->fromFile(CONFIG_PATH.DS.'config.xml');
                        $class = $class['category'];
                         ?>
                    <?php foreach ($class as $key => $val) : ?>
                    	<li>
                    		<a href="<?= $this->escapehtml('/classlist/'.$key)?>">
                    			<?= $this->escapehtml($val)?>
                    		</a>
                      </li>
                    <?php endforeach; ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">    						
      					   <?php $session = new \Zend\Session\Container('User');?>
      					   <?php if($session->offsetExists('account')) : ?>
      					   <li>
      							<a href="<?= $this->escapehtml('/logout')?>">
      								<span class="glyphicon glyphicon-off"></span>注销
      							</a>
      					   </li>
      					   <?php else :?>
      					   <li>
      							<a href="<?= $this->escapehtml('/login')?>">
      								<span class="glyphicon glyphicon-user"></span>登录
      							</a>
      					   </li>
      					   <?php endif;?>
    					 </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
            		<div class="copyright">
            			<div class="copyimg">
            				<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/cn/">
            					<img alt="知识共享许可协议" style="border-width:0" src="/images/88x31.png" />
            				</a>
            			</div>
            			<div class="copylice">
            				<small>
            				除另有声明，本站所有内容皆采用<br/>
            				<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/cn/">
            				知识共享许可协议3.0(中国大陆)</a>进行授权。
            				</small>
            			</div>     			           			            			
            		</div>
                <p>&copy; 2015 - <?php echo date('Y') ?> by <?= $this->translate('Skeleton Application')?>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
