<?php
$this->headtitle('Home');
$mottos = $this->mottos;
$blgcount = $this->blgcount;
$unitcut = count($mottos);
?>
<style>
body {
	padding-top: 0px;
	padding-bottom:0px;
}
.carousel-inner img {
    -webkit-filter: grayscale(90%);
    filter: grayscale(90%); /* make all photos black and white */
    width: 100%; /* Set width to 100% */
    margin: auto;
}
.carousel-caption h3 {
    color: #fff !important;
	font-size: 36px;
}
.carousel-caption a {
    color: #fff !important;
	 text-decoration:none;
}
.carousel-caption p {
    font-size: 18px;
}
</style>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        
        	<?php for($i=0;$i<$blgcount;$i++) :?>
        		<?php if(0 == $i) :?>
        		   <li data-target="#myCarousel" data-slide-to="<?= $i?>" class="active"></li> 
        		   <?php continue;?>     		
        		<?php endif;?>
        			<li data-target="#myCarousel" data-slide-to="<?= $i?>"></li>
        	<?php endfor;?>      
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
    	<?php $count=0;?>
    	<?php foreach($this->blogs as $blog):?>
    		<?php $index = mt_rand()%$unitcut;?>
    		<?php if(0 == $count):?>
        <div class="item active">
            <a href="<?= $this->escapehtml('/viewblog/'.$blog->id)?>">
            	   <img src="<?= $this->escapehtml($blog->image)?>" alt="<?= $this->escapehtml($blog->title)?>">
            </a>
            <div class="carousel-caption">
                <h3>
                	<a href="<?= $this->escapehtml('/viewblog/'.$blog->id)?>">
                		<?= $this->escapehtml($blog->title)?>               	
                	</a>
                </h3>
                <p><?= $mottos[$index]['motto'].'<br/>---'.$mottos[$index]['author']?></p>
            </div>
        </div>
        	<?php $count++;?>
          <?php continue;?>
        <?php endif;?>
        <div class="item">
            <a href="<?= $this->escapehtml('/viewblog/'.$blog->id)?>">
            	   <img src="<?= $this->escapehtml($blog->image)?>" alt="<?= $this->escapehtml($blog->title)?>">
            </a>
            <div class="carousel-caption">
                <h3>
                	<a href="<?= $this->escapehtml('/viewblog/'.$blog->id)?>">
                		<?= $this->escapehtml($blog->title)?>               	
                	</a>
                </h3>
                <p><?= $mottos[$index]['motto'].'<br/>---'.$mottos[$index]['author']?></p>
            </div>
        </div>
        <?php $count++;?>
        <?php endforeach;?>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<script type="text/javascript">
	$(document).ready(function(){		
		$('.carousel-inner img').height($(this).height());
		$(window).resize(function(){
			$('.carousel-inner img').height($(this).height());
		});
	});
</script>