<?php
$blog = $this->blog;
@$title = $blog->title;
$this->headtitle($title);
$motto = $this->motto;
$config = new \Zend\Config\Reader\Xml();
$allconfig = $config->fromFile(CONFIG_PATH.DS.'config.xml');
$class = $allconfig['category'];
$cate='';
foreach($class as $k => $v){
    if($k === $blog->classify){
        $cate = $v;
        break;
    }
}
?>
<div class="row content">
    <div class="col-sm-3 sideleft">
        <div class="img">
            <img class="img-circle" src="<?= '/images/uploads/'.$allconfig['headimg']?>" alt="it's me" height="140" width="140"/>
        </div>
        <div class="text-center text-muted blogname">
            <h4 class="text-info">天启崇祯的博客</h4>
            <p><?= $motto['motto']?><br/>---<?= $motto['author']?></p>
        </div>
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search Blog..">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
        </div>
    </div>

    <div class="col-sm-9 sideright">
        <nav class="crumbs" role="navigation">
        	<ol>
        		<li class="crumb">
        			<a href="<?= $this->url('home')?>">首页</a>
        		</li>
        		<li class="crumb">
        			<a href="<?= $this->escapehtml('/classlist/'.$blog->classify)?>"><?= $cate?></a>
        		</li>
        		<li class="crumb cut">
        			<span><?= $blog->title?></span>
        		</li>
        	</ol>
        </nav>

        <h2><?= $blog->title?></h2>
        <h5 class="text-muted"><span class="glyphicon glyphicon-time"></span> Post at <?= $blog->ctime?></h5>
        <h5><span class="label label-default"><?= $blog->classify?></span></h5>
        <div class="row">
        	<div class="continc col-sm-12">
        		<?= $blog->content?>
        	</div>
        </div>

        <hr>
        <h4>评论:</h4>
        <form role="form" id="myform">
            <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-default">提交</button>
        </form>
        <br><br>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    //阻止提交表单行为
    $('#myform').submit(function(e){
        e.preventDefault();
    });

    //$('.continc img').addClass('img-responsive');
     //图片等比例缩放
    var w=$('.sideright').width();
    var h=$('.sideright').height();
    var imgs = $('.continc img');
    for(var i=0;i<imgs.length;i++){
        if(imgs[i].width > w){        	 
        	 var img_h = Math.floor((w/imgs[i].width)*imgs[i].height);
        	 $(imgs[i]).height(img_h);
        	 $(imgs[i]).width(w);
        }
     }
});
</script>