<?php

$title = '后台管理';
$this->headtitle($title);
?>
<div class="row">
	<div class="col-sm-2">
	<div class="panel panel-default">
		<div class="panel-heading"><?php echo $this->escapehtml($title); ?></div>
		<div class="panel-body">
		<ul class="nav nav-pills nav-stacked">
			<li>
				<a href="<?php echo $this->escapehtml('/blog');?>">博客管理</a>
			</li>
			<li>
				<a href="<?php echo $this->escapehtml('/upfiles');?>">上传图片管理</a>
			</li>
			<li>
				<a href="<?php echo $this->escapehtml('/motto');?>">格言管理</a>
			</li>
			<li>
				<a href="<?php echo $this->escapehtml('/backup');?>">数据备份</a>
			</li>
			<li>
				<a href="<?php echo $this->escapehtml('/rpnexus');?>">设置权限</a>
			</li>
		</ul>
		</div>
	</div>
	</div>

	<div class="col-sm-10">
		<h2 class="text-muted"><?php echo $this->escapehtml("用户管理"); ?></h2>
		<hr/>
		<p><a class="btn btn-info" href="<?php echo $this->escapehtml('/admin/add');?>">添加用户</a></p>
		<table class="table">
		<thead>
 		<tr>
  			<th>ID</th>
  			<th>账户</th>
  			<th>邮箱</th>
  			<th>角色名</th>
  			<th>状态</th>
  			<th>创建时间</th>
  			<th>最近修改时间</th>
  			<th>操作</th>
 		</tr>
		</thead>
		<tbody>
		<?php foreach ($this->data as $post) : ?>
		<tr>
          	<td><?= $this->escapeHtml($post['id']); ?></td>
  			<td><?= $this->escapeHtml($post['account']); ?></td>
  			<td><?= $this->escapeHtml($post['email']); ?></td>
  			<td><?= $this->escapeHtml($post['role_name']); ?></td>
  			<td><?= $this->escapeHtml($post['status']); ?></td>
  			<td><?= $this->escapeHtml($post['created_on']); ?></td>
  			<td><?= $this->escapehtml($post['modified_on']); ?></td>
  			<td>
  				<button class="btn btn-default btn-sm" onclick="deluser('<?= $post['id']; ?>')"
  				data-toggle="tooltip" title="删除">
  				<span class="glyphicon glyphicon-trash"></span>
  				</button>
  			</td>
 		</tr>
		<?php endforeach; ?>
		</tbody>
		</table>
	</div>
</div>
<script type="text/javascript">
function deluser(id){
	if(confirm('你要确定还是取消')){
        var del = 'yes';
        $.post("/admin/deluser?id="+Math.floor(Math.random()*1000), 
			    { "id":id,"confirm":del},
				function(data){
				    if(data.status){
					   alert(data.message);
					   location.reload();
					}else{
						alert(data.message);
					}
				}, "json");
    }
}
$(document).ready(function(){
	$('[data-toggle="tooltip"]').tooltip();//bootstrap浮动提示
});
</script>